#
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py
#

## EVAL

CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv

CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv

CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PointPipl-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS_PointPipl.py --evaluate_adv
