# no_BoxAttention
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.01 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.02 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.03 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.04 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.05 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.06 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.07 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.08 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.09 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.10 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py

## Eval
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.01 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.02 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.03 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.04 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.05 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.06 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.07 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.08 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.09 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_BoxAttention --fixedEPS 0.3 --attach_rate 0.10 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv

