
## no_GradSorted
#
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.6 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.7 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.8 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.9 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 1.0 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
#
### EVAL
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.6 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.7 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.8 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.9 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 1.0 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
#
# --attach_rate 0.0
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.0 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=2 python test.py --subsample_num 323 --strategy PGD-filterOnce-no_GradSorted --fixedEPS 0.3 --attach_rate 0.0 --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt ../checkpoints/pv_rcnn_8369.pth --batch_size 1 --cfg_pyfile cfgs/adv_pv_rcnn/pv_rcnn-voxels_adv-AdaptiveEPS.py --evaluate_adv
