
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py

### EVAL


CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.1 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.2 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.3 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.4 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv

CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=3 python test.py --subsample_num 323 --strategy light-PGD-filterOnce --fixedEPS 0.5 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
