# OppoPSel_v2
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.0 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.6 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.7 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.8 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.9 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 1.0 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py

CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.0 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.1 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.2 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.3 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.4 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.5 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.6 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.7 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.8 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 0.9 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
CUDA_VISIBLE_DEVICES=1 python test.py --subsample_num 323 --strategy PGD-filterOnce-OppoPSel_v2 --fixedEPS 0.5 --attach_rate 1.0 --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt ../checkpoints/pointpillar_7728.pth --batch_size 1 --cfg_pyfile cfgs/adv_pointpillar/pointpillar-adv-AdaptiveEPS.py --evaluate_adv
